# Generated by Django 5.2 on 2025-12-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, max_length=66)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount_eth', models.DecimalField(decimal_places=18, max_digits=32)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tx_hash'], name='wallet_api__tx_hash_cb33ff_idx'), models.Index(fields=['from_address'], name='wallet_api__from_ad_9a5906_idx'), models.Index(fields=['created_at'], name='wallet_api__created_a27bef_idx')],
            },
        ),
    ]
