# Generated by Django 5.2 on 2025-12-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broadcasted',
            field=models.BooleanField(default=False),
        ),
    ]
